fix(android/cairo): drop ctime_r
Android already declares ctime_r in time.h, so the fallback is unneeded.
Additionally, the detection is buggy so HAVE_CTIME_R doesn't properly trigger on
cross-compiled Android builds causing:

    cairo-ps-surface.c:106:14: error: static declaration of 'ctime_r' follows
    non-static declaration

We need to drop the extra declaration

Signed-off-by: Skyler Grey <skyler.grey@collabora.com>
Change-Id: I470efa71086717ff550041b59c6a5f576a6a6964
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/9334
Reviewed-by: Karthik Godha <karthik.godha@collabora.com>
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/10705