WOPIFileInfo still needs to be a complete type here
e7dd8397857660c2b6b2d7d814c755964226f6ca "wsd: include less in
DocumentBroker.hpp." had started to cause

> In file included from wsd/AIChatSession.cpp:19:
> In file included from wsd/AIChatSession.hpp:24:
> In file included from wsd/DeckSpec.hpp:26:
> In file included from engine/workdir/UnpackedTarball/poco/include/Poco/JSON/Object.h:22:
> In file included from engine/workdir/UnpackedTarball/poco/include/Poco/JSON/Array.h:23:
> In file included from engine/workdir/UnpackedTarball/poco/include/Poco/Dynamic/Var.h:25:
> In file included from engine/workdir/UnpackedTarball/poco/include/Poco/OrderedMap.h:31:
> In file included from engine/workdir/UnpackedTarball/poco/include/Poco/ordered_map.h:32:
> In file included from ~/gcc/inst/lib/gcc/x86_64-pc-linux-gnu/17.0.0/../../../../include/c++/17.0.0/memory:80:
> ~/gcc/inst/lib/gcc/x86_64-pc-linux-gnu/17.0.0/../../../../include/c++/17.0.0/bits/unique_ptr.h:90:16: error:
>       invalid application of 'sizeof' to an incomplete type 'WOPIFileInfo'
>    90 |         static_assert(sizeof(_Tp)>0,
>       |                       ^~~~~~~~~~~
> ~/gcc/inst/lib/gcc/x86_64-pc-linux-gnu/17.0.0/../../../../include/c++/17.0.0/bits/unique_ptr.h:408:4: note:
>       in instantiation of member function
>       'std::default_delete<WOPIFileInfo>::operator()' requested here
>   408 |           get_deleter()(std::move(__ptr));
>       |           ^
> ./wsd/DocumentBroker.hpp:494:73: note: in instantiation of member function
>       'std::unique_ptr<WOPIFileInfo>::~unique_ptr' requested here
>   494 |   ...std::unique_ptr<WOPIFileInfo> wopiFileInfo = nullptr);
>       |                                                   ^
> ./wsd/DocumentBroker.hpp:64:7: note: forward declaration of 'WOPIFileInfo'
>    64 | class WOPIFileInfo;
>       |       ^

etc.

Signed-off-by: Stephan Bergmann <stephan.bergmann@collabora.com>
Change-Id: I623ba6e137d852e24c7fdcec477a0ea81f1bbf6d
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/14779
Reviewed-by: Noel Grandin <noel.grandin@collabora.com>
Tested-by: Jenkins CPCI <releng@collaboraoffice.com>