cypress: click the Show Sheet OK button, not the div around it
Hide/Show sheet failed in desktop calc4/sheet_operation_spec.js with:

    Timed out retrying after 60000ms: Not enough elements found. Found '1', expected '2'.
    cypress_test/integration_tests/common/calc_helper.js:326 assertNumberofSheets

and on the retry:

    CypressError: Timed out retrying after 60050ms: `cy.click()` failed because this element:

    `<div class="unotoolbutton jsdialog ui-content unospan insertsheet no-label" tabindex="-1" id="insertsheet" data-cooltip="Insert sheet">...</div>`

    is being covered by another element:

    `<div class="jsdialog-overlay dimmed" id="modal-dialog-show-sheets-modal-overlay">...</div>`

The wrapper div #show-sheets-modal-response is enabled at once, but
the button inside it is enabled later, on a following animation
frame. On a loaded node the click reached the button while it was
still disabled, so the click was dropped and the dialog stayed open.

so click #show-sheets-modal-response-button, which Cypress waits on
until it is enabled

since:

commit c2fa51eaba2845d6b119ce85ad1c164de5cfee35
Date:   Mon May 26 10:43:56 2025 +0000

    LayoutingService: put disabled state updates in queue

Signed-off-by: Caolán McNamara <caolan.mcnamara@collabora.com>
Change-Id: Iad0b47d28c6c3113e7e59f7ad4adcb59e4cb69f6
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/14304
Tested-by: Jenkins CPCI <releng@collaboraoffice.com>
Reviewed-by: Noel Grandin <noel.grandin@collabora.com>