make unit-insert-delete more stable
When inserting a page (.uno:InsertPage), sometimes `status:` messages
can be received twice (see example at the end of the commit message).
So this repeated status: message is consumed later which results in
failed assertion:
ERROR: Assertion failure: 11 - it != currentPartHashes.size() Expected currentPartHashes.size() [11] == 11 - it [10]

Drain the stale mesages after the insert slide loop ends.

These repeated status: messages only seems to occur during
.uno:InsertSlide, and that too inconsistently. So the other assertions
should be fine.

Example:
wsd-1038737-1038737 2026-03-11 13:26:33.357119 [ coolwsd ] DBG  #28: UnitInsertDelete Matched message [status:]: status: {"mode": 0,"readonly": false,"partdimensions": [{"height":11906,"width":15875},{"height":11906,"width":15875}],"viewid": 4,"height": 11906,"width": 15875,"parts": [{ "masterPageCount": 1, "mode": 0, "gridSnapEnabled": true, "gridVisible": false, "gridCoarseWidth": 2540, "gridCoarseHeight": 2540, "innerSpacesX": 10, "innerSpacesY": 10, "visible": 1, "selected": 0, "width": 28000, "height": 21000, "leftBorder": 0, "rightBorder": 0, "upperBorder": 0, "lowerBorder": 0, "name": "Slide 1", "hash": 46}, { "masterPageCount": 1, "mode": 0, "gridSnapEnabled": true, "gridVisible": false, "gridCoarseWidth": 2540, "gridCoarseHeight": 2540, "innerSpacesX": 10, "innerSpacesY": 10, "visible": 1, "selected": 1, "width": 28000, "height": 21000, "leftBorder": 0, "rightBorder": 0, "upperBorder": 0, "lowerBorder": 0, "name": "Slide 2", "hash": 106}],"selectedpart": 1,"partscount": 2,"type": "presentation"}| test/WebSocketSession.hpp:357
wsd-1038737-1038737 2026-03-11 13:26:33.357127 [ coolwsd ] TST  UnitInsertDelete [testInsertDelete] (+10460ms): it :1| UnitInsertDelete.cpp:105

wsd-1038737-1038737 2026-03-11 13:26:33.508585 [ coolwsd ] DBG  #28: UnitInsertDelete Matched message [status:]: status: {"mode": 0,"readonly": false,"partdimensions": [{"height":11906,"width":15875},{"height":11906,"width":15875}],"viewid": 4,"height": 11906,"width": 15875,"parts": [{ "masterPageCount": 1, "mode": 0, "gridSnapEnabled": true, "gridVisible": false, "gridCoarseWidth": 2540, "gridCoarseHeight": 2540, "innerSpacesX": 10, "innerSpacesY": 10, "visible": 1, "selected": 0, "width": 28000, "height": 21000, "leftBorder": 0, "rightBorder": 0, "upperBorder": 0, "lowerBorder": 0, "name": "Slide 1", "hash": 46}, { "masterPageCount": 1, "mode": 0, "gridSnapEnabled": true, "gridVisible": false, "gridCoarseWidth": 2540, "gridCoarseHeight": 2540, "innerSpacesX": 10, "innerSpacesY": 10, "visible": 1, "selected": 1, "width": 28000, "height": 21000, "leftBorder": 0, "rightBorder": 0, "upperBorder": 0, "lowerBorder": 0, "name": "Slide 2", "hash": 106}],"selectedpart": 1,"partscount": 2,"type": "presentation"}| test/WebSocketSession.hpp:357
wsd-1038737-1038737 2026-03-11 13:26:33.508589 [ coolwsd ] TST  UnitInsertDelete [testInsertDelete] (+10612ms): it :2| UnitInsertDelete.cpp:105

Signed-off-by: Mohit Marathe <mohit.marathe@collabora.com>
Change-Id: I70b7d8bd414d27fb5e7f436ea7b1d9a87b469687
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/12327
Reviewed-by: Caolán McNamara <caolan.mcnamara@collabora.com>
Tested-by: Caolán McNamara <caolan.mcnamara@collabora.com>