cypress: don't show the event-delay watchdog dialog during ci
  Top toolbar tests.
    "before each" hook for "Apply font size.":

  CypressError: Timed out retrying after 60050ms: `cy.click()` failed because this element:
  <button class="ui-tab notebookbar" id="View-tab-label" role="tab" aria-controls="View" aria-label="View" aria-selected="false" tabindex="-1">View</button>
  is being covered by another element:
  <div class="jsdialog-overlay dimmed" id="modal-dialog-cool_alert-overlay">...</div>

  Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `Top toolbar tests.`

    cypress_test/integration_tests/common/desktop_helper.js:416
      414 |   var userInterfaceMode = win['0'].userInterfaceMode;
      415 |   if (userInterfaceMode === 'notebookbar') {
    > 416 |     cy.cGet('#View-tab-label').click();
          |                                ^
      417 |     getNbIcon('toggleuimode', 'View').click();

The covering overlay is the event-delay watchdog's cool_alert
("Event handling has been delayed for an unexpectedly long time")
getting shown under CI load.

The watchdog modal is present since:

commit 38835801790497e0a5bd1a0984aab77766690829
Date:   Thu Feb 13 11:14:08 2025 +0000

    Introduce an event delay watchdog debugging feature

Signed-off-by: Caolán McNamara <caolan.mcnamara@collabora.com>
Change-Id: I2dbdfdb1d558b5c28dcf8a77ff7de3f5d7113424
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/3565
Reviewed-by: Noel Grandin <noel.grandin@collabora.com>
Tested-by: Jenkins CPCI <releng@collaboraoffice.com>
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/3953