run the ReportWhenIdle idle twice and reply from the second run
lighthouse calc/a11y_notebookbar_spec.js failed with:

    A11yValidatorException: ... arrowgrid > startarrowstyle > startarrowstyle-input-notebookbar': element in widget of type 'startarrowstyle-input-notebookbar' is missing label

The first run drains the bindings, which queues widget updates on
JSDialog idles, so the reply now comes from a second run that goes
after those updates have been sent.

Signed-off-by: Caolán McNamara <caolan.mcnamara@collabora.com>
Change-Id: Ifd506f7dffeb6bdbb7ee0ed048e726435b216c48
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/13598
Reviewed-by: Noel Grandin <noel.grandin@collabora.com>
Tested-by: Jenkins CPCI <releng@collaboraoffice.com>