cypress: update the writer4 stylebar_spec baseline screenshots
The stored images no longer match what is rendered now, so the spec
fails with:

    Error: The 'style_added' image is different. Threshold limit of '0.07' exceeded: '0.07'
     at Context.eval (cypress-visual-regression/dist/command.js:171:0)

Signed-off-by: Caolán McNamara <caolan.mcnamara@collabora.com>
Change-Id: Ia41110031ed416db7ffd581ec6176a563d5cbbb1
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/13070
Reviewed-by: Noel Grandin <noel.grandin@collabora.com>
Tested-by: Jenkins CPCI <releng@collaboraoffice.com>
(cherry picked from commit 936356bba33bd25fa9f7d3377ae1e9a6709ef4dd)
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/13282