fix(android/afdko): use stdint for uint32_t
In the afdko build, sha1.c derives uint32_t from limits.h ranges:

    #if ULONG_MAX == 4294967295U
    typedef unsigned long int uint32_t;
    #elif UINT_MAX == 4294967295U
    typedef unsigned int uint32_t;
    ...

on 32-bit Android targets this picks `unsigned long int` which conflicts
with uint32_t (`unsigned int`) from stdint.h:

    sha1.c:10:27: error: typedef redefinition with different types
        ('unsigned long' vs '__uint32_t' (aka 'unsigned int'))

we can just include stdint.h instead, avoiding the issue entirely...
as this is in an external source we need to make a .patch for it
and register it to be included on Android. On 64-bit Android it's
effectively a no-op, so there's not a problem with including it on all
architectures...

Signed-off-by: Skyler Grey <skyler.grey@collabora.com>
Change-Id: I926051859b065baa694af8d4388f3e326a6a6964
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/9321
Reviewed-by: Karthik Godha <karthik.godha@collabora.com>
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/10704