uitest: let the new comment become active before replying to it
seen in ci as:

  ERROR: test_tdf133348 (tdf133348.tdf133348.test_tdf133348)
  File ".../engine/sw/qa/uitest/writer_tests7/tdf133348.py", line 35, in test_tdf133348
      self.assertEqual(xEnum.nextElement().Author.strip(), 'Known Author')
  tdf133348.com.sun.star.container.NoSuchElementException: SwXFieldEnumeration::nextElement at sw/source/core/unocore/unofield.cxx:3114

probably since:

commit 9b7b7d8c840b593e6d03f35233148b686530a3af
Date:   Sun Aug 23 19:55:06 2026 +0200

    uitest: stop setting Writer options through the Tools - Options dialog

The comment from .uno:InsertAnnotation only becomes the active comment
in SwPostItMgr's CalcHdl, which runs from a posted user event.
.uno:ReplyComment without an id replies to the active comment, so if
it runs before that event no reply is added. The options dialog used
to run the event loop between the two commands, set_config does not.

Not reproduced locally, 16 runs under heavy load passed.

Signed-off-by: Caolán McNamara <caolan.mcnamara@collabora.com>
Change-Id: Id99b67c17bc75cac280126cf9e4ee7ffdf58efe6
Reviewed-on: https://gerrit.collaboraoffice.com/c/online/+/14310
Tested-by: Jenkins CPCI <releng@collaboraoffice.com>
Reviewed-by: Miklos Vajna <vmiklos@collabora.com>